openapi: 3.0.0
info:
    description: 'The description of the application'
    title: 'App title'
    version: '1.0'
tags:
    -
        name: test_reso
    -
        name: Other
    -
        name: Auth
paths:
    /:
        get:
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {  }
                404:
                    description: 'Resource not found'
            tags:
                - Other
        post:
            responses:
                201:
                    description: 'Resource created'
                400:
                    description: 'Invalid body'
            tags:
                - Other
    /auth:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
            responses:
                200:
                    description: 'Returns JSON Web Token (JWT)'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token: { type: string }
                403:
                    description: 'Invalid credentials'
            tags:
                - Auth
    /test_reso:
        post:
            responses:
                201:
                    description: 'Resource created'
                400:
                    description: 'Invalid body'
            tags:
                - test_reso
        get:
            parameters:
                -
                    name: id
                    in: query
                    schema:
                        type: string
                -
                    name: text
                    in: query
                    schema:
                        type: string
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                404:
                    description: 'Resource not found'
            tags:
                - test_reso
    '/test_reso/{id}':
        put:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                200:
                    description: 'Resource updated'
                400:
                    description: 'Invalid body'
                404:
                    description: 'Resource not found'
            tags:
                - test_reso
        delete:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                204:
                    description: 'Resource deleted'
                404:
                    description: 'Resource not found'
            tags:
                - test_reso
        get:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                404:
                    description: 'Resource not found'
            tags:
                - test_reso
