openapi: 3.0.0
info:
    description: 'The description of the application'
    title: 'App title'
    version: '1.0'
tags:
    -
        name: custom
    -
        name: Authentication
paths:
    /:
        get:
            tags:
                - custom
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {  }
                404:
                    description: 'Resource not found'
    /asd:
        get:
            tags:
                - custom
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {  }
                404:
                    description: 'Resource not found'
    /auth:
        post:
            tags:
                - Authentication
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token: { type: string }
                403:
                    description: 'Invalid credentials'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
