openapi: 3.0.0
info:
    description: 'The description of the application'
    title: 'App title'
    version: '1.0'
tags:
    -
        name: post
    -
        name: users
    -
        name: Auth
    -
        name: Other
    -
        name: comment
    -
        name: comment_post
paths:
    /:
        get:
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {  }
                404:
                    description: 'Resource not found'
            tags:
                - Other
        post:
            responses:
                201:
                    description: 'Resource created'
                400:
                    description: 'Invalid body'
            tags:
                - Other
    /auth:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
            responses:
                200:
                    description: 'Returns JSON Web Token (JWT)'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token: { type: string }
                403:
                    description: 'Invalid credentials'
            tags:
                - Auth
    /comment:
        post:
            responses:
                201:
                    description: 'Resource created'
                400:
                    description: 'Invalid body'
            tags:
                - comment
        get:
            parameters:
                -
                    name: id
                    in: query
                    schema:
                        type: string
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                404:
                    description: 'Resource not found'
            tags:
                - comment
    '/comment/{id}':
        put:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                200:
                    description: 'Resource updated'
                400:
                    description: 'Invalid body'
                404:
                    description: 'Resource not found'
            tags:
                - comment
        delete:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                204:
                    description: 'Resource deleted'
                404:
                    description: 'Resource not found'
            tags:
                - comment
        get:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                404:
                    description: 'Resource not found'
            tags:
                - comment
    /comment_post:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                comment_id:
                                    type: integer
                                post_id:
                                    type: integer
            responses:
                201:
                    description: 'Resource created'
                400:
                    description: 'Invalid body'
            tags:
                - comment_post
        get:
            parameters:
                -
                    name: id
                    in: query
                    schema:
                        type: string
                -
                    name: comment_id
                    in: query
                    schema:
                        type: string
                -
                    name: post_id
                    in: query
                    schema:
                        type: string
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    comment_id: { type: integer }
                                    post_id: { type: integer }
                404:
                    description: 'Resource not found'
            tags:
                - comment_post
    '/comment_post/{comment_id}/{post_id}':
        delete:
            parameters:
                -
                    name: comment_id
                    in: path
                    required: true
                    schema:
                        type: integer
                -
                    name: post_id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                204:
                    description: 'Resource deleted'
                404:
                    description: 'Resource not found'
            tags:
                - comment_post
    /post:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                content:
                                    type: string
            responses:
                201:
                    description: 'Resource created'
                400:
                    description: 'Invalid body'
            tags:
                - post
        get:
            parameters:
                -
                    name: id
                    in: query
                    schema:
                        type: string
                -
                    name: content
                    in: query
                    schema:
                        type: string
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                404:
                    description: 'Resource not found'
            tags:
                - post
    '/post/{id}':
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                content:
                                    type: string
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                200:
                    description: 'Resource updated'
                400:
                    description: 'Invalid body'
                404:
                    description: 'Resource not found'
            tags:
                - post
        delete:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                204:
                    description: 'Resource deleted'
                404:
                    description: 'Resource not found'
            tags:
                - post
        get:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                404:
                    description: 'Resource not found'
            tags:
                - post
    /users:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
                                roles:
                                    type: string
            responses:
                201:
                    description: 'Resource created'
                400:
                    description: 'Invalid body'
            tags:
                - users
        get:
            parameters:
                -
                    name: id
                    in: query
                    schema:
                        type: string
                -
                    name: username
                    in: query
                    schema:
                        type: string
                -
                    name: roles
                    in: query
                    schema:
                        type: string
                -
                    name: password
                    in: query
                    schema:
                        type: string
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                                    username: { type: string }
                                    roles: { type: string }
                404:
                    description: 'Resource not found'
            tags:
                - users
    '/users/{id}':
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
                                roles:
                                    type: string
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                200:
                    description: 'Resource updated'
                400:
                    description: 'Invalid body'
                404:
                    description: 'Resource not found'
            tags:
                - users
        delete:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                204:
                    description: 'Resource deleted'
                404:
                    description: 'Resource not found'
            tags:
                - users
        get:
            parameters:
                -
                    name: id
                    in: path
                    required: true
                    schema:
                        type: integer
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                                    username: { type: string }
                                    roles: { type: string }
                404:
                    description: 'Resource not found'
            tags:
                - users
