openapi: 3.0.0
info:
    description: 'The description of the application'
    title: 'App title'
    version: '1.0'
tags:
    -
        name: Other
    -
        name: Authentication
paths:
    /:
        get:
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {  }
                404:
                    description: 'Resource not found'
            tags:
                - Other
    /auth:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
            responses:
                200:
                    description: 'Retrieves resource data'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token: { type: string }
                403:
                    description: 'Invalid credentials'
            tags:
                - Authentication
